# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
