# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20170113_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
