# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20170114_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='createdtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='updatedtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
