# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20170115_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
