# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_place_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='lon',
            new_name='lng',
        ),
    ]
